StudentManagementSystem/Models/Result.cs
using System.ComponentModel.DataAnnotations;

namespace StudentManagementSystem.Models
{
    public class Result
    {
        public Guid Id { get; set; }
        public Guid StudentId { get; set; } //Required foreign key property
        public Guid SubjectId { get; set; }
        [Required]
        public int Mark { get; set; }
        public string Grade { get; set; } = null!;

        // Navigation properties
        public Student Student { get; set; } = null!; //Required reference navigation to principal
        public Subject Subject { get; set; } = null!;
    }
}

StudentManagementSystem/Controllers/FileController.cs
using System.IO;
using Microsoft.AspNetCore.Mvc;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using StudentManagementSystem.Models;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Kernel.Colors;



namespace StudentManagementSystem.Controllers
{
    public class FileController : Controller
    {
        private readonly string _active = "active";
        private readonly IResultRepository _resultRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ISubjectRepository _subjectRepository;

        public FileController(IResultRepository resultRepository,ISubjectRepository subjectRepository, IStudentRepository studentRepository)
        {
            _resultRepository = resultRepository;
            _subjectRepository = subjectRepository;
            _studentRepository = studentRepository;
        }
        public async Task<IActionResult> GeneratePDF(Class? klass, string? name, string? subject)
        {

            List<Subject> subjects = await _subjectRepository.GetAllSubject();
            List<Result> results = await _resultRepository.GetAllResult();
            //IEnumerable<Student> students = await _studentRepository.GetAllStudent();
            int numberOfSubject = subjects.Count;
            ViewData["result"] = _active;
            ViewData["name"] = name;
            byte[] pdfBytes;

            IEnumerable<Result>? model;
            if (klass != null)
            {
                List<Student> students = await _studentRepository.GetClassStudent((Class)klass);
                model = await _resultRepository.GetClassResult((Class)klass);
                // Generate PDF using iText 7
                using (MemoryStream ms = new MemoryStream())
                {
                    PdfWriter writer = new PdfWriter(ms);
                    PdfDocument pdf = new PdfDocument(writer);
                    Document document = new Document(pdf);
                    Paragraph header =new Paragraph("Class Result")
                        .SetTextAlignment(TextAlignment.CENTER)
                        .SetFontSize(20);
                    Paragraph studentClass = new Paragraph(klass.ToString())
                        .SetTextAlignment(TextAlignment.CENTER)
                        .SetFontSize(10);
                    LineSeparator ls = new LineSeparator(new SolidLine());


                    // Table
                    Table table = new Table(numberOfSubject+1, false);
                    Cell cell11 = new Cell(1, 1)
                       .SetBackgroundColor(ColorConstants.GRAY)
                       .SetTextAlignment(TextAlignment.CENTER)
                       .Add(new Paragraph("Name"));
                    table.AddCell(cell11);
                    foreach(var subj in subjects)
                    {                      
                        table.AddCell(new Cell(1, 1)
                           .SetBackgroundColor(ColorConstants.GRAY)
                           .SetTextAlignment(TextAlignment.CENTER)
                           .Add(new Paragraph(subj.Name)));
                    }

                    foreach (var student in students)
                    {
                        table.AddCell(new Cell(1, 1)
                           //.SetBackgroundColor(ColorConstants.GRAY)
                           .SetTextAlignment(TextAlignment.CENTER)
                           .Add(new Paragraph(student.Name)));
                        foreach (var sub in subjects)
                        {
                            Result res = await _resultRepository.GetResultByStudentbySubject(student, sub);
                            string mark = res != null ? res.Mark.ToString() : String.Empty;
                            table.AddCell(new Cell(1, 1)
                              //.SetBackgroundColor(ColorConstants.GRAY)
                              .SetTextAlignment(TextAlignment.CENTER)
                              .Add(new Paragraph(mark)));
                        }
                    }

                    document.Add(header);
                    document.Add(ls);
                    document.Add(studentClass);
                    document.Add(table);
                    document.Close();
                    pdfBytes = ms.ToArray();
                }

                return File(pdfBytes, "application/pdf");

            }
            else if (name != null)
            {
                List<Result> studentResults = await _resultRepository.GetStudentResult(name);
                Result result = studentResults.FirstOrDefault();

                using (MemoryStream ms = new MemoryStream())
                {
                    PdfWriter writer = new PdfWriter(ms);
                    PdfDocument pdf = new PdfDocument(writer);
                    Document document = new Document(pdf);
                    Paragraph header = new Paragraph($"{result.Student.Name} Results")
                        .SetTextAlignment(TextAlignment.CENTER)
                        .SetFontSize(20);
                    Paragraph studentKlass = new Paragraph($"Class: {result.Student.Class}")
                        .SetTextAlignment(TextAlignment.CENTER)
                        .SetFontSize(20);
                    LineSeparator ls = new LineSeparator(new SolidLine());


                    document.Add(header);
                    document.Add(studentKlass);
                    document.Add(ls);
                    foreach (var res in studentResults)
                    {
                        document.Add( new Paragraph($"{res.Subject.Name}: {res.Mark}")
                        .SetTextAlignment(TextAlignment.LEFT)
                        .SetFontSize(15));
                    }
                    document.Close();
                    pdfBytes = ms.ToArray();
                }
                return File(pdfBytes, "application/pdf");
            }

            model = await _resultRepository.GetAllResult();
            return View("ListResult", model);
        }

    }
}

StudentManagementSystem/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentManagementSystem.Dto;
using StudentManagementSystem.Models;
using System.ComponentModel.DataAnnotations;

namespace StudentManagementSystem.Controllers
{
    public class ResultController : Controller
    {
        private readonly string _active = "active";
        private readonly IResultRepository _resultRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ISubjectRepository _subjectRepository;

        public ResultController(IResultRepository resultRepository, IStudentRepository studentRepository, ISubjectRepository subjectRepository)
        {
            _resultRepository = resultRepository;
            _studentRepository = studentRepository;
            _subjectRepository = subjectRepository;
        }
        [HttpGet]
        public async Task<IActionResult> AddResult()
        {
            ViewData["result"] = _active;
            var students = await _studentRepository.GetAllStudent();
            var subjects = await _subjectRepository.GetAllSubject();
            // Create a ViewModel to hold both lists
            var viewModel = new AddResultViewModel
            {
                Students = students,
                Subjects = subjects
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddResult(ResultViewModel resultViewModel)
        {
            ViewData["result"] = _active;
            if (ModelState.IsValid)
            {
                int mark = (int)resultViewModel.Mark;
                Result result = new()
                {
                    StudentId = (Guid)resultViewModel.StudentId,
                    SubjectId = (Guid)resultViewModel.SubjectId,
                    Mark = mark,
                    Grade = CalculateGrade(mark),
                };
                await _resultRepository.AddResult(result);
                return RedirectToAction("GetResult", "Result", new { id = result.Id });
            }

            var students = await _studentRepository.GetAllStudent();
            var subjects = await _subjectRepository.GetAllSubject();
            // Create a ViewModel to hold both lists
            var viewModel = new AddResultViewModel
            {
                Students = students,
                Subjects = subjects
            };
            return View(viewModel);
        }

        //public async Task<IActionResult> ListResult()
        //{
        //    ViewData["result"] = _active;
        //    IEnumerable<Result>? model = await _resultRepository.GetAllResult();
        //    return View(model);
        //}

        public async Task<IActionResult> ListResult(Class? klass, string? name, string? subject)
        {
            ViewData["result"] = _active;
            ViewData["name"] = name;
            IEnumerable<Result>? model;
            if (klass != null)
            {
                model = await _resultRepository.GetClassResult((Class)klass);
                return View(model);
            }
            else if(name != null)
            {
                model = await _resultRepository.GetStudentResult(name);
                return View(model);
            }
            else if (subject != null)
            {
                model = await _resultRepository.SearchSubjectResult(subject);
                return View(model);
            }
            
            model = await _resultRepository.GetAllResult();
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> GetResult(Guid id)
        { 
            ViewData["result"] = _active;
            if (id == null)
            {
                return RedirectToAction("ListResult", "Result");
            }
            if (ModelState.IsValid)
            {
                Result result = await _resultRepository.GetResultById(id);
                if (result == null)
                {
                    Response.StatusCode = 404;
                    return View("StudentNotFound", id);
                }
                return View(result);
            }
            return RedirectToAction("ListResult", "Result");
        }

        [HttpGet]
        public async Task<IActionResult> EditResult(Guid id)
        {
            ViewData["result"] = _active;
            if (id == null)
            {
                return RedirectToAction("StudentList", "Student");
            }
            Result result = await _resultRepository.GetResultById(id);
            if (result == null)
            {
                Response.StatusCode = 404;
                return View("ResultNotFound", id);
            }
            var students = await _studentRepository.GetAllStudent();
            var subjects = await _subjectRepository.GetAllSubject();
            // Create a ViewModel to hold both lists
            var viewModel = new EditResultViewModel
            {
                Students = students,
                Subjects = subjects,
                StudentId = result.Student.Id,
                SubjectId = result.Subject.Id,
                Mark = result.Mark,
                Id = result.Id
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditResult(ResultViewModel model)
        {
            ViewData["result"] = _active;
            if (ModelState.IsValid)
            {
                Result result = await _resultRepository.GetResultById(model.Id);
                result.StudentId = (Guid)model.StudentId;
                result.SubjectId = (Guid)model.SubjectId;
                result.Mark = (int)model.Mark;
                result.Grade = CalculateGrade((int)model.Mark);

                await _resultRepository.UpdateResult(result);
                return RedirectToAction("GetResult", "Result", new { id = model.Id });
            }
            var students = await _studentRepository.GetAllStudent();
            var subjects = await _subjectRepository.GetAllSubject();
            // Create a ViewModel to hold both lists
            var viewModel = new EditResultViewModel
            {
                Students = students,
                Subjects = subjects,
                StudentId = model.StudentId,
                SubjectId = model.SubjectId,
                Mark = model.Mark,
                Id = model.Id
            };

            return View(viewModel);
        }

        public async Task<IActionResult> DeleteResult(Guid id)
        {
            ViewData["result"] = _active;
            if (id == null)
            {
                return RedirectToAction("ListResult", "Result");
            }
            Result result = await _resultRepository.GetResultById(id);
            if (result == null)
            {
                Response.StatusCode = 404;
                return View("ResultNotFound", id);
            }
            await _resultRepository.DeleteResult(id);
            return RedirectToAction("ListResult", "Result");
        }
        private string CalculateGrade(int mark)
        {
            // Implement your logic here to calculate the grade based on the mark
            // For example:
            if (mark >= 90)
            {
                return "A";
            }
            else if (mark >= 80)
            {
                return "B";
            }
            else if (mark >= 70)
            {
                return "C";
            }
            else if (mark >= 60)
            {
                return "D";
            }
            else
            {
                return "F";
            }
        }
    }
}

StudentManagementSystem/Views/Result/AddResult.cshtml
@model AddResultViewModel;

@{
    ViewData["Title"] = "Subject";
}
<div class="container text-start">
    <div class="row">
        <partial name="_SideNavPartial" />
        <div class="col border">
            <div class="container text-start">
                <div class="border p-2 mt-3">
                    <a asp-controller="Result" asp-action="ListResult" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                        <i class="bi bi-list"></i>
                        Result List
                    </a>
                </div>
                <div class="d-flex justify-content-center">
                    <div>
                        <h4 class="mt-3">Create Subject</h4>
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <form class="mt-2" style="width:350px;" method="POST" asp-action="AddResult" asp-controller="Result">
                            <div class="mb-3">
                                <label asp-for="ResultViewModel.SubjectId"></label>
                                <div>
                                    <select class="form-select" asp-for="ResultViewModel.SubjectId">
                                        <option value="">Select a subject</option>
                                        @foreach (var subject in Model.Subjects)
                                        {
                                            <option value="@subject.Id">@subject.Name</option>
                                        }
                                    </select>
                                    <span asp-validation-for="ResultViewModel.SubjectId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label asp-for="ResultViewModel.StudentId"></label>
                                <div>
                                    <select class="form-select" asp-for="ResultViewModel.StudentId">
                                        <option value="">Select a Student</option>
                                        @foreach (var student in Model.Students)
                                        {
                                            <option value="@student.Id">@student.Name</option>
                                        }
                                    </select>
                                    <span asp-validation-for="ResultViewModel.StudentId" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label asp-for="ResultViewModel.Mark" class="form-label"></label>
                                <input class="form-control" asp-for="ResultViewModel.Mark" placeholder="Mark" />
                                <span asp-validation-for="ResultViewModel.Mark" class="text-danger"></span>
                            </div>
            
                            <button type="submit" class="btn btn-danger">Add Result</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudentManagementSystem/Views/Result/EditResult.cshtml
@model EditResultViewModel;

@{
    ViewData["Title"] = "Subject";
}
<div class="container text-start">
    <div class="row">
        <partial name="_SideNavPartial" />
        <div class="col border">
            <div class="container text-start">
                <div class="border p-2 mt-3">
                    <a asp-controller="Result" asp-action="ListResult" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                        <i class="bi bi-list"></i>
                        Result List
                    </a>
                </div>
                <div class="d-flex justify-content-center">
                    <div>
                        <h4 class="mt-3">Create Subject</h4>
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <form class="mt-2" style="width:350px;" method="POST" asp-action="EditResult" asp-controller="Result">
                            <input hidden asp-for="Id" />
                            <div class="mb-3">
                                <label asp-for="SubjectId"></label>
                                <div>
                                    <select class="form-select" asp-for="SubjectId">
                                        <option value="">Select a subject</option>
                                        @foreach (var subject in Model.Subjects)
                                        {
                                            <option value="@subject.Id">@subject.Name</option>
                                        }
                                    </select>
                                    <span asp-validation-for="SubjectId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label asp-for="StudentId"></label>
                                <div>
                                    <select class="form-select" asp-for="StudentId">
                                        <option value="">Select a Student</option>
                                        @foreach (var student in Model.Students)
                                        {
                                            <option value="@student.Id">@student.Name</option>
                                        }
                                    </select>
                                    <span asp-validation-for="StudentId" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label asp-for="Mark" class="form-label"></label>
                                <input class="form-control" asp-for="Mark" placeholder="Mark" />
                                <span asp-validation-for="Mark" class="text-danger"></span>
                            </div>

                            <button type="submit" class="btn btn-danger">Update Result</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudentManagementSystem/Views/Result/GetResult.cshtml
@model Result;

@{
    ViewData["Title"] = "Result";
}
<div class="container text-start">
    <div class="row">
        <partial name="_SideNavPartial" />
        <div class="col border">
            <div class="container text-start">
                <div class="border p-2 mt-3">
                    <a asp-controller="Result" asp-action="ListResult" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                        <i class="bi bi-list"></i>
                        Result List
                    </a>
                </div>
                <div class="d-flex justify-content-center mt-3">
                    <div>
                        <h2 class="fs-2" style="font-weight:bold;">Result Detail</h2>
                        <dl class="row" style="font-size:1.2em;">
                            <dt class="col-sm-3">Name:</dt>
                            <dd class="col-sm-9">@Model.Student.Name</dd>

                            <dt class="col-sm-3">Class:</dt>
                            <dd class="col-sm-9">@Model.Student.Class</dd>

                            <dt class="col-sm-3">Subject:</dt>
                            <dd class="col-sm-9">@Model.Subject.Name</dd>

                            <dt class="col-sm-3">Mark:</dt>
                            <dd class="col-sm-9">@Model.Mark</dd>

                            <dt class="col-sm-3">Grade:</dt>
                            <dd class="col-sm-9">@Model.Grade</dd>
                        </dl>
                        <div>
                            <button type="button" class="btn btn-primary">Edit</button>
                            <button type="button" class="btn btn-danger">Delete</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

StudentManagementSystem/Views/Result/ListResult.cshtml
@model IEnumerable<Result>;
@{
    ViewData["Title"] = "Student";
    string klassValue = Context.Request.Query["klass"].ToString();
    string nameValue = Context.Request.Query["name"].ToString();
    string subjectValue = Context.Request.Query["subject"].ToString();
}
<div class="container text-start">
    <div class="row">
        <partial name="_SideNavPartial" />
        <div class="col border">
            <div class="container text-start">
                <div class="border p-2 mt-3">
                    <a asp-controller="Result" asp-action="AddResult" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                        <i class="bi bi-person-plus-fill"></i>
                        Add New Result
                    </a>
                    <span class="ms-5">
                        <a asp-controller="Result" asp-action="ListResult" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            All
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="0" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            JSS1
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="1" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            JSS2
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="2" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            JSS3
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="3" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            SSS1
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="4" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            SSS2
                        </a>
                        <a asp-controller="Result" asp-action="ListResult" asp-route-klass="5" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            SSS3
                        </a>
                    </span>
                    <div class="row">
                        <form asp-action="ListResult" asp-controller="Result" method="GET" class="col">
                            <input type="text" id="name" name="name" value="@ViewData["name"]" />
                            <button type="submit">Search by Name</button>
                        </form>

                        <form asp-action="ListResult" asp-controller="Result" method="GET" class="col">
                            <input type="text" id="subject" name="subject" value="@ViewData["subject"]" />
                            <button type="submit">Search by Subject</button>
                        </form>

                        <a asp-controller="File" asp-action="GeneratePDF" asp-route-klass="@klassValue" asp-route-name="@nameValue" asp-route-subject="@subjectValue"  target="_blank" class="btn btn-light" data-mdb-ripple-init data-mdb-ripple-color="dark">
                            Download PDF
                        </a>
                    </div>
                </div>
                <table class="table align-middle mb-0 bg-white">
                    <thead class="bg-light ">
                        <tr>
                            <th>Name</th>
                            <th>Class</th>
                            <th>Subject</th>
                            <th>Grade</th>
                            <th>Mark</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Result result in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                                             alt=""
                                             style="width: 45px; height: 45px"
                                             class="rounded-circle" />
                                        <div class="ms-3">
                                            <p class="fw-bold mb-1">@result.Student.Name</p>
                                            <p class="text-muted mb-0"></p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="fw-normal mb-1">@result.Student.Class</p>
                                    <p class="text-muted mb-0"></p>
                                </td>
                                <td>
                                    <p class="fw-normal mb-1">@result.Subject.Name</p>
                                    <p class="text-muted mb-0"></p>
                                    @* <span class="badge badge-success rounded-pill d-inline">Active</span> *@
                                   @*  <p class="fw-normal mb-1">@student.DateOfBirth?.ToString("dd-MM-yyyy")</p> *@

                                </td>
                                <td>
                                    <p class="fw-normal mb-1 @((result.Grade == "F") ? "text-danger" : "")">@result.Grade</p>
                                    <p class="text-muted mb-0"></p>
                                </td>
                                <td>
                                    <p class="fw-normal mb-1">@result.Mark</p>
                                    <p class="text-muted mb-0"></p>
                                </td>


                                <td>
                                    <a asp-controller="Result" asp-action="GetResult" asp-route-id="@result.Id" type="button" class="btn btn-link btn-sm btn-rounded">
                                        View
                                    </a>
                                    <a asp-controller="Result" asp-action="EditResult" asp-route-id="@result.Id" type="button" class="btn btn-link btn-sm btn-rounded">
                                        Edit
                                    </a>
                                    <a asp-controller="Result" asp-action="DeleteResult" asp-route-id="@result.Id" type="button" class="btn btn-link btn-sm btn-rounded">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>